[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build]
command = "npm run build"   # Use your Vite build command here
publish = "dist"    # Replace with the path to your Vite build output directory

